import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Local sidebar — overrides the base image's default.
 *
 * Manual rather than autogenerated, deliberately. Autogeneration takes its
 * sections from folders, so grouping the specs would mean moving files — and
 * that changes every published URL, breaks every relative cross-reference, and
 * runs into the positional numbering CLAUDE.md warns about. Naming doc ids here
 * gives the same sections at no URL cost.
 *
 * Ids are paths under docs/docs/ without the extension **and without the numeric
 * filename prefix** — Docusaurus strips it when deriving the id, which is the
 * same reason it does not appear in the URL. So `engine/01-vision.md` is
 * `engine/vision`, while `engine/MVP.md`, having no prefix, is `engine/MVP`.
 *
 * The prefixes stay on disk, where they still order the files; the reading order
 * below is stated outright instead of being inferred from them. That is why
 * `core` precedes `story-graph-kind`: the core is the shorter way in, and the
 * specs say so.
 *
 * Adding a page means adding it here. The trade for stable URLs is that a new
 * file is invisible until it is listed; an id that does not resolve fails the
 * build, so a typo cannot pass quietly.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Orientation',
      collapsed: false,
      items: ['engine/vision', 'engine/architecture'],
    },
    {
      type: 'category',
      label: 'Contracts',
      collapsed: false,
      items: [
        'engine/core',
        'engine/story-graph-kind',
        'engine/observability',
        'engine/extensibility',
        'engine/replay',
        'engine/session-capture',
        'engine/clients',
        'engine/simulation-kind',
        'engine/content-packs',
        'engine/world-graph-kind',
      ],
    },
    {
      type: 'category',
      label: 'Delivery',
      collapsed: false,
      items: ['engine/MVP', 'engine/TODO', 'engine/OPEN-QUESTIONS', 'engine/CHANGELOG'],
    },
    {
      type: 'category',
      label: 'Working on It',
      collapsed: false,
      items: ['guide/engine-package', 'guide/documentation-site'],
    },
  ],
};

export default sidebars;
